(function(g){var window=this;'use strict';var J3=function(a){a.publish("cardstatechange",a.Ik()&&a.To()?1:0)},K3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},jnb=function(a){var b=g.xs(a);
a=g.As(a);return new g.ls(b.x,b.y,a.width,a.height)},knb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.kC(a,b,function(){g.lC(e);c.apply(a,arguments)},d)},N3=function(a){a=g.fb(a);
delete L3[a];g.md(L3)&&M3&&M3.stop()},mnb=function(){M3||(M3=new g.Uu(function(){lnb()},20));
var a=M3;a.isActive()||a.start()},lnb=function(){var a=g.kb();
g.bd(L3,function(b){nnb(b,a)});
g.md(L3)||mnb()},O3=function(a,b,c,d){g.nv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},nnb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;onb(a,a.progress);1==a.progress?(a.j=0,N3(a),a.onFinish(),a.Yq()):a.isPlaying()&&a.FL()},onb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},pnb=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},P3=function(a,b,c,d,e){O3.call(this,b,c,d,e);
this.element=a},qnb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
P3.call(this,a,b,c,d,e)},rnb=function(a){return Math.pow(a,3)},snb=function(a){return 3*a*a-2*a*a*a},tnb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},Q3=function(a){return a.baseUrl||null},R3=function(a,b){return g.tt(g.Ir(a,b),function(c){return!!c})},unb=function(a,b,c){function d(qa){var ka=qa.hovercardButton;
if(!ka)return null;ka=ka.subscribeButtonRenderer;if(!ka)return null;var va=f(ka.unsubscribedButtonText),da=f(ka.subscribedButtonText);if(ka.subscribed){var W=f(ka.subscriberCountWithUnsubscribeText);var Na=f(ka.subscriberCountText)}else W=f(ka.subscriberCountText),Na=f(ka.subscriberCountWithSubscribeText);var y=null;if(qa.signinEndpoint){y=K3(qa,"signinEndpoint","webNavigationEndpointData","url");if(!y){var aa,Ja;y=null==(Ja=g.U(null==(aa=ka.signInEndpoint)?void 0:aa.commandMetadata,g.D2))?void 0:
Ja.url}if(!y)return null}return va&&(da||y)?{subscribed:ka.subscribed,subscribeText:va,subscribeCount:W,unsubscribeText:da,unsubscribeCount:Na,enabled:ka.enabled,signinUrl:y,classic:qa.useClassicSubscribeButton}:null}
function e(qa){if(qa){var ka=[],va=qa.videoId;va&&ka.push("v="+va);(va=qa.playlistId)&&ka.push("list="+va);(qa=qa.startTimeSeconds)&&ka.push("t="+qa);return"/watch?"+ka.join("&")}}
function f(qa){if(!qa)return null;var ka=qa.simpleText;return ka?ka:qa.runs?g.Ir(qa.runs,function(va){return va.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,D=null,F=null,G=null,L=null,N=null;if("VIDEO"===h)g.U(l,g.UF)?m=g.U(l,g.UF).url:(N=g.U(l,g.aT),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.UF)?m=g.U(l,g.UF).url:(N=g.U(l,g.aT),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=K3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((F=K3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=K3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=K3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ea="";if(b.metadata){var ra=f(b.metadata);ra&&(ea=ra)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ea,callToAction:f(b.callToAction),qW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,eE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:D,isSubscribe:w,targetUrl:m||null,x8:n,sessionData:R?{itct:R}:null,Wca:q,DC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:R3(b.impressionUrls||[],Q3),k8:R3(b.hovercardShowUrls||[],Q3),clickUrls:R3(l.loggingUrls||[],Q3),visualElement:g.$E(b.trackingParams),productPrice:G,additionalFeesText:L,watchEndpoint:N||null}},vnb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:R3(a.impressionUrls||[],Q3),elements:R3(a.elements||[],function(d,e){return unb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.$E(a.trackingParams));return c},wnb=function(a){g.NV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.SR(a)||g.UR(a);this.events=new g.xK(this);g.O(this,this.events);this.events.T(this.player,g.GJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.HJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Vb);this.events.T(window,"focus",this.kba);this.load();var b=g.If("STYLE");(g.xf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},xnb=function(a){return a.player.getVideoData().Lf?"current":a.Z?"new":"current"},S3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},ynb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=vnb(f,xnb(a))));T3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Yx;d&&(c.postParams={ad_tracking:d});if(b=g.vUa(b))if(b=g.ye(b),b=g.ke(b))a.C=g.CB(b,c)},T3=function(a,b,c){c=void 0===c?!0:c;
a.player.uf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&znb(a);c=[];d=new g.FJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.hU(a.player,a.B.element,4),a.D=new g.hG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Anb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.hU(a.player,f.element,4);var h=new g.FJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Bnb(a,f,e)}else g.fF(new g.BC("buildEndscreenElement null",
e))}a.player.nf(c);a.Vb()}},znb=function(a){var b=g.aF(),c=g.bF();
c&&b&&a.endscreen.visualElement&&g.gB(g.nF)(void 0,c,b,a.endscreen.visualElement)},Anb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:U3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:V3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.tv(b.title||"")},xa:b.title},{I:"div",S:b.eE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:U3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:V3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.tv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:V3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.tv(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:U3(b)}]};c=new g.V(c);var d=g.yf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.bv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.vW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.tv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:V3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:U3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:Cnb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.DC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.tv(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:V3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:U3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.bv(c.element,"ytp-ce-placeholder");return c},U3=function(a){if(a.qW)var b=a.qW.thumbnails;
return Cnb(b?b[b.length-1].url:null)},Cnb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Bnb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.bv(b.element,"ytp-ce-force-expand"),W3(a,c.id,!0)):(g.dv(b.element,"ytp-ce-force-expand"),g.dv(b.element,"ytp-ce-element-hover"),W3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Dnb(a,b,c)});
b.listen("mouseleave",function(){Enb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.bv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Fnb(a,c,m)});
b.listen("keypress",function(m){Fnb(a,c,m)});
b.listen("focus",function(){Dnb(a,b,c)});
b.listen("blur",function(){Enb(a,b,c)});
b.listen("touchstart",function(){Dnb(a,b,c)});
var l=g.Af("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.dv(b.element,"ytp-ce-element-hover");g.dv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Af("ytp-sb-subscribe",b.element));d(g.Af("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Fnb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.av(d,"ytp-ce-element");){g.av(d,"subscribe-label")&&Gnb(a,b);
if(g.av(d,"ytp-ce-channel-subscribe"))return;d=g.Sf(d)}if(!d||g.av(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Enb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Wca)Gnb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ye(V3(a,b.targetUrl)),g.PG(g.ke(c),void 0,b.sessionData);else{var e=g.dS(a.player.U())||a.player.getVideoData().Lf,f=function(){var h=V3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.lB(h);e&&n&&(n.v||
n.list)?a.player.Fo(n.v,l,n.list,!1,void 0,m||void 0):g.eya(h,l)};
Gnb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},V3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.kS(a)+b}else return"";return b},Dnb=function(a,b,c){g.av(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.bv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Uu(function(){g.bv(b.element,"ytp-ce-element-hover")},200)).start():g.bv(b.element,"ytp-ce-element-hover"),X3(a,c.k8),W3(a,c.id,!0))},Enb=function(a,b,c){g.dv(b.element,"ytp-ce-element-hover");
g.dv(b.element,"ytp-ce-force-expand");W3(a,c.id,!1)},W3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.mv(a.j[e].element,"ytp-ce-element-shadow-show",c)},X3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||S3(a))c&&c();else{b=Hnb(a,b);var e=0,f=!1,h=new g.Uu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.VD(b[a],d)}},Gnb=function(a,b,c){X3(a,b.clickUrls,c);
(a=g.bF())&&b.x8&&g.uF(a,b.visualElement)},Hnb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Inb(b[d],c));return a},Inb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Jnb=function(a){return"string"===typeof a?a:""},Y3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Knb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},Z3=function(a){return a.value?a.value:null},$3=function(a){if(!a)return null;
var b=g.ye(Jnb(a.value));b=g.ke(b);if(!b)return null;var c=Y3(a.target,Lnb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Knb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Mnb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Pnb=function(a){if(!a)return null;
var b=Y3(a.type,Nnb),c=Y3(a.trigger,Onb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=$3(a?a:null);return b?new Mnb(b,c,a):null},Qnb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Rnb=function(a,b){return g.Db(a.action,b)},Snb=function(a,b){this.context=a;
this.j=b},Tnb=function(a){return a.customMessage?a4("div","iv-card-message",a.customMessage):""},b4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Unb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(a4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},a4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.tv(c);return{I:a,X:b,xa:c}},Vnb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.NC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.NC+");");c.dir=g.tv(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},c4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},Wnb=function(a,b){this.merchant=a;
this.price=b},Xnb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Ynb=function(a,b){return b?b:Xnb(a)?"current":"new"},d4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Va=new Map;this.Za=new Map;this.context.J.addEventListener(g.GJ("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.HJ("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},e4=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.GL(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},Znb=function(a){var b;
return(null==(b=g.U(a,g.UF))?0:b.url)?g.U(a,g.UF).url:(a=g.U(a,g.aT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},f4=function(a,b,c){return{UX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
A0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
WK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},$nb=function(a,b,c){d4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.Ma=this.Hb=this.C=this.isInitialized=!1;this.cards=[];this.sb=this.Z=this.La=this.G=this.Ta=this.j=null;this.oa=[];this.ra=this.N=this.If=this.Da=null;this.K=0;this.Ga=new g.Uu(function(){},c.W.Il?4E3:3E3);
g.O(this,this.Ga);this.bb=new g.Uu(function(){});
g.O(this,this.bb);this.Ba=new Snb(c,function(e,f,h,l,m,n){e4(d,e,f,h,l,m,n)});
this.Y=new g.V({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.O(this,this.Y);this.D=this.Y.element;this.Xa=new g.hG(this.Y,330);g.O(this,this.Xa);this.Jb=g.Af("iv-drawer-header-text",this.D);this.B=g.Af("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Hb&&g4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Hb=d.C)&&h4(d)});
this.Qa=new g.xK(this);g.O(this,this.Qa);this.J.addEventListener("videodatachange",this.Us.bind(this))},aob=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){g4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){h4(a)});
var c=b.headerText;g.Uf(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.$E(b.trackingParams);a.N=g.$E(b.closeTrackingParams);a.If=g.$E(b.iconTrackingParams)},bob=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.IF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},Wo:null,Ij:e.trackingParams?g.$E(e.trackingParams):null,If:f&&f.trackingParams?g.$E(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
NC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};i4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.IF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:j4(a,c,b,f),sponsored:!1,bj:f4(f,e,f.command),Wo:f.trackingParams?g.$E(f.trackingParams):null,Ij:e.trackingParams?g.$E(e.trackingParams):null,If:l&&l.trackingParams?g.$E(l.trackingParams):null,imageUrl:k4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.IF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,NC:null,title:f.title?g.IF(f.title):"",customMessage:f.callToAction?g.IF(f.callToAction):"",url:g.U(f.command,g.UF).url?$3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.UF).url}):null,onClickCommand:null};i4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.IF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,e),sponsored:!1,bj:f4(e,f,e.endpoint),Wo:e.trackingParams?g.$E(e.trackingParams):null,Ij:f.trackingParams?g.$E(f.trackingParams):null,If:l&&l.trackingParams?g.$E(l.trackingParams):null,channelId:g.U(e.endpoint,g.pT).browseId,customMessage:e.customText?g.IF(e.customText):null,profileImageUrl:k4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.IF(e.channelName):"",metaInfo:[e.subscriberCountText?g.IF(e.subscriberCountText):""],url:$3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.pT).canonicalBaseUrl?g.U(e.endpoint,g.pT).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.pT).browseId}),onClickCommand:null};i4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.IF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,e),sponsored:!1,bj:f4(e,f,e.action),Wo:e.trackingParams?g.$E(e.trackingParams):null,Ij:f.trackingParams?g.$E(f.trackingParams):null,If:l&&l.trackingParams?g.$E(l.trackingParams):null,lG:k4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.IF(e.customMessage):null,playlistVideoCount:g.IF(e.playlistVideoCount),title:e.playlistTitle?g.IF(e.playlistTitle):"",metaInfo:[e.channelName?g.IF(e.channelName):
"",e.videoCountText?g.IF(e.videoCountText):""],url:$3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Znb(e.action)}),onClickCommand:null};i4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.IF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,e),sponsored:!1,bj:f4(e,f,e.action),Wo:e.trackingParams?g.$E(e.trackingParams):null,Ij:f.trackingParams?g.$E(f.trackingParams):null,If:l&&l.trackingParams?g.$E(l.trackingParams):null,lG:k4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.IF(e.lengthString):null,customMessage:e.customMessage?g.IF(e.customMessage):null,title:e.videoTitle?g.IF(e.videoTitle):"",metaInfo:[e.channelName?g.IF(e.channelName):
"",e.viewCountText?g.IF(e.viewCountText):""],isLiveNow:!!e.badge,url:$3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Znb(e.action)}),onClickCommand:null};i4(a,b)}}}}}a.K++},k4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},j4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},dob=function(a,b){if(b=cob(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Df.id),g.Rf(b.bN),g.Hb(a.cards,b),a.gH(),l4(a)},g4=function(a,b,c){if(!a.C){a.Xa.show();
a.Ta=new g.Uu(function(){g.bv(a.context.J.getRootNode(),g.fZ.IV_DRAWER_OPEN)},0);
a.Ta.start();a.Qa.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.bF();d&&a.Da&&a.N&&g.sF(d,[a.Da,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.LY||(f.LY=!0,eob(a.context.logger,f.Df.bj.UX,b)),d&&g.sF(d,[f.Df.Wo]);J3(a.J);c&&(a.G=new g.Uu(function(){a.La=a.Z;a.sb.focus()},330),a.G.start())}},h4=function(a){a.C&&(a.Xa.hide(),g.qC(a.Qa),g.dv(a.context.J.getRootNode(),g.fZ.IV_DRAWER_OPEN),a.C=!1,J3(a.J),a.G&&a.G.stop(),a.G=new g.Uu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},gob=function(a){g.cv(a.Gb(),
[g.fZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.hU(a.J,a.D,5);fob(a);a.Z=g.Af("ytp-cards-button",a.J.getRootNode());a.sb=g.Af("iv-drawer-close-button",a.D);a.isInitialized=!0},fob=function(a){var b=g.Af("iv-drawer-close-button",a.D);
a.context.j.listen(b,"click",a.U5,a);a.context.j.listen(a.B,"touchend",function(){a.Ga.start()});
a.context.j.listen(a.B,"scroll",a.s6,a);a.context.B.subscribe("onHideControls",function(){a.Ma=!0});
a.context.B.subscribe("onShowControls",function(){a.Ma=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Ma=g.av(a.J.getRootNode(),"ytp-autohide")});
a.oa.push(g.iE("iv-button-shown",a.P8,a));a.oa.push(g.iE("iv-button-hidden",a.O8,a));hob(a)},hob=function(a){a.oa.push(g.iE("iv-teaser-shown",a.F2,a));
a.oa.push(g.iE("iv-teaser-hidden",a.Q8,a));a.oa.push(g.iE("iv-teaser-clicked",a.E2,a));a.Ab=!0},iob=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.Gjb))?void 0:c.targetId)?(a.ra=b,!0):!1},job=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.VSa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.i1a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},i4=function(a,b){if(!iob(a,b)||job(a,b)){var c=kob(a,b);
if(c){var d={Df:b,bN:c.element,LY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||hob(a),dob(a,b.id),c=a.findLastIndex(d),g.Pb(a.cards,c,0,d));else{a.isInitialized||gob(a);dob(a,b.id);var e=a.findLastIndex(d);g.Pb(a.cards,e,0,d);c.Ia(a.B,e);a.gH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,l4(a),lob(a,d),g4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&mob(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){mob(a,d)}),l4(a))}}},kob=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Vnb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?Z3(b.url)||"":""},V:[b4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[a4("h2",void 0,b.title),d]}]}]};c=new g.V(c);c4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:Z3(b.url)||"","data-ytid":b.channelId},V:[b4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Tnb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Unb(b)]}]}]};c=new g.V(c);c4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:Z3(b.url)||""},V:[b4(b.lG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Tnb(b),a4("h2","iv-card-primary-link",b.title),Unb(b)]}]}]};
c=new g.V(c);c4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Vnb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?Z3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[a4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.If("span");g.Uf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Md(d,"adInfo");c4(a,g.zf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:Z3(c))||""},V:[b4(b.lG,d),{I:"div",S:"iv-card-content",V:[Tnb(b),a4("h2","iv-card-primary-link",b.title),Unb(b),f]}]}]};c=new g.V(e);c4(a,g.zf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},nob=function(a){if(a.j)return"productListing"===a.j.Df.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Jr(a.cards,function(c){return"productListing"===c.Df.type})}return g.Jr(a.cards,function(c){return"productListing"===c.Df.type})},l4=function(a){g.mv(a.J.getRootNode(),"ytp-cards-shopping-active",nob(a))},mob=function(a,b){if(!g.av(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.bF(),d=a.j?a.j.Df.If:a.If;
c&&d&&g.tF(c,[d]);a.j=b;l4(a)}(c=a.isInitialized&&"none"==a.Gb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.Df.teaserDurationMs&&a.J.kB(!0,{teaserText:b.Df.teaserText,durationMs:b.Df.teaserDurationMs,onClickCommand:b.Df.onClickCommand});a.bb.isActive()||((!a.C||!a.Ga.isActive()&&a.Ma)&&lob(a,b),a.bb.start(910+b.Df.teaserDurationMs))}},lob=function(a,b){a.Y.Db?(b=new O3([0,
a.B.scrollTop],[0,b.bN.offsetTop],600,snb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.EF(a.Y,!0),a.B.scrollTop=b.bN.offsetTop,g.EF(a.Y,!1))},m4=function(a){return a.j&&a.j.Df?a.j.Df:a.cards[0]&&a.cards[0].Df?a.cards[0].Df:null},cob=function(a,b){return g.Db(a.cards,function(c){return c.Df.id===b})},n4=function(a,b,c){d4.call(this,a,b);
this.annotation=c;this.isActive=!1},oob=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},o4=function(a,b,c){n4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},pob=function(a,b){var c=void 0===c?0:c;
var d=jnb(b).width;g.vs(b,d);c=new qnb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,rnb);g.O(a,c);a.context.C.listen(c,"begin",function(){g.Bs(b,!0)});
c.play()},sob=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.vW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ia(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Bs(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.os(l,"right",b.image_width+"px");g.Kf(a.Gb(),l);a.C=new g.Uu(function(){qob(a,h,l)},500);
g.O(a,a.C);a.context.j.listen(a.Gb(),"mouseover",function(){rob(a,h,l,f,b.image_height)});
a.context.j.listen(a.Gb(),"mouseout",function(){a.C.start()})}},rob=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.As(b);a.j||(b.style.width=g.us(f.width,!0),c.style.width=g.us(f.width,!0));g.os(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.os(d,"right","1px");a.D=!0;g.Bs(b,!0);a.G=new g.Uu(function(){g.bv(this.Gb(),"iv-branding-active")},0,a);
a.G.start()}},qob=function(a,b,c){g.dv(a.Gb(),"iv-branding-active");
a.K=new g.Uu(function(){g.Bs(b,!1);a.j||(c.style.width=g.us(0,!0))},250);
a.K.start();a.D=!1},tob=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},uob=function(a,b,c){n4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.Uu(function(){d.j.setAttribute("aria-hidden","true");g.Bs(d.C,!1);g.Bs(d.B,!0)},700,this);
g.O(this,this.G)},xob=function(a,b,c){c.stopPropagation();
vob(a);wob(a,b);a.j.focus()},yob=function(a){a.isCollapsed||a.Z||a.D||(g.bv(a.Gb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},vob=function(a){a.G.stop();
a.isCollapsed&&(g.lv(a.Gb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Bs(a.B,!1),g.Bs(a.C,!0))},wob=function(a,b){a.D||(a.D=g.yg(function(){zob(this);
yob(this)},b,a))},zob=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},Aob=function(a){this.J=a},eob=function(a,b,c){b&&(c?p4(a,b.map(function(d){return g.Ju(d,c)})):p4(a,b))},p4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.VD(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Bob=function(a){g.NV.call(this,a);
var b=this;this.oa=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new Aob(this.player);this.D=new g.xK(this);this.G=this.K=null;this.events=new g.xK(this);this.Ug=this.Y=this.j=null;this.ra=[];g.O(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.G2,this);this.subscribe("resize",this.KJ,this);this.player.U().Ma.subscribe("vast_info_card_add",this.PZ,this);g.O(this,this.events);this.Ba=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.O(this,this.B);g.hU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",Ka:["ytp-iv-video-content"]});g.O(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.Vt()&&this.load();var c=this.createElement({I:"style"});(g.xf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Cob=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Bs(a,!1);return a},Dob=function(a,b){b=!b.isCued()&&!g.uG(b,1024);
g.EF(a.B,b);g.EF(a.C,b)},Eob=function(a,b,c){a.Z=!0;
a.G=g.CB(b,c)},Fob=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Fob(a,e))}return c},Job=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().Ma.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.vB(h)&&h.responseXML?h.responseXML:null)&&Gob(a,h)}};
g.JC()&&(d.onFinish=Hob(a,d.onFinish));d.postParams={ic_only:"1"};Iob(d,c);a.Z=!0;g.CB(b.Ta,d)}}},Iob=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.lH&&(a.postParams.ic_coll=b.lH);b.cN&&(a.postParams.ic_xml=b.cN);b.bL&&(a.postParams.ic_track=b.bL)},Kob=function(a){var b=new g.V({I:"div"});
g.Bs(b.element,!1);var c=new $nb(a.player,b.element,q4(a));g.O(c,b);b.Ia(a.B.element);c.UF();return c},Mob=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.oa=!0,Lob(a,b),b.headerText&&a.Ug&&(c=g.IF(b.headerText),a.Ug.setAttribute("title",c))},q4=function(a){if(!a.Y){var b=new tnb(a);
g.O(a,b);var c=new g.Ip(a);g.O(a,c);a.Y=new tob(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.qj)}return a.Y},Gob=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.bF();if(e){var f=g.aF();f&&g.gB(g.Ewa)(void 0,e,f,[g.$E(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Fob(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Y3(f.type,Nob),p=Y3(f.style,Oob),q=Jnb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Pnb;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var D=f(A.value);
D&&l.push(D)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Qnb(m,n,p,v,r):null}else e=null}catch(ra){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=Cob(f),L=null;switch(l.type){case "branding":if(f.player.U().De)break;f.B.element.appendChild(G);L=new o4(G,q4(f),l);break;case "promotion":g.hU(f.player,G,4),L=new uob(G,q4(f),l)}L&&L.UF();if(f=L)g.O(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Kob(a),g.O(a,a.j));if("card"===e.type){G=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={UX:f.impression,click:f.click,close:f.close,A0:f.teaser_impression,WK:f.teaser_click},l=e.tracking_params||{},L=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Wo:l.card?g.$E(l.card):null,Ij:l.teaser?g.$E(l.teaser):null,If:l.icon?g.$E(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:$3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};i4(G,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,
Wo:l.card?g.$E(l.card):null,Ij:l.teaser?g.$E(l.teaser):null,If:l.icon?g.$E(l.icon):null,lG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:$3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};i4(G,c);break;case "productListing":e.signin_url&&(L=$3({target:"current",value:e.signin_url}));N=[];for(var R=e.offers||[],ea=0;ea<R.length;ea++)N.push(new Wnb(g.af(R[ea].merchant),
g.af(R[ea].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Wo:l.card?g.$E(l.card):null,Ij:l.teaser?g.$E(l.teaser):null,If:l.icon?g.$E(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,NC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:$3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),fpb:L,epb:e.signin_title?e.signin_title:void 0,dpb:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};i4(G,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Wo:l.card?g.$E(l.card):
null,Ij:l.teaser?g.$E(l.teaser):null,If:l.icon?g.$E(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,NC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:$3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};i4(G,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Wo:l.card?g.$E(l.card):null,Ij:l.teaser?g.$E(l.teaser):null,If:l.icon?g.$E(l.icon):null,lG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:$3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},i4(G,c)}}else aob(a.j,e);c=!0}}c&&
(J3(a.player),a.KJ())},Lob=function(a,b){var c=!1;
a.j||(a.j=Kob(a),g.O(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(bob(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.wT(f)||(c=a.j,d=b.headerText?g.IF(b.headerText):"",g.Uf(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.$E(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.$E(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.If=b.icon.infoCardIconRenderer.trackingParams?g.$E(b.icon.infoCardIconRenderer.trackingParams):null,a.KJ());J3(a.player)}},Pob=function(a,b,c,d,e){if(!a.player.U().De){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.pT)&&g.U(b.navigationEndpoint,g.pT).browseId&&f.push(new Mnb("openUrl","click",new Knb("/channel/"+g.U(b.navigationEndpoint,g.pT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.qT)){d.channel_id=g.U(b.subscribeButton,g.qT).channelId;var l;b=g.U(b.subscribeButton,g.qT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.IF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.IF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.IF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.IF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.D2))?void 0:m.url)||"";l={subscribeText:g.IF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.IF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Qnb(c,"branding","branding",f,d);l=Cob(a);a.B.element.appendChild(l);f=new o4(l,q4(a),f);f.UF();g.O(f,f);a.N[c]=f}},Hob=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ra.push(g.Mu.Ni(function(){b.apply(null,g.oa(c))}))}},Qob=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.aU.prototype.kB=g.fa(28,function(a,b){var c=g.dW(this.xb());c&&c.kB(a,b)});
var L3={},M3=null;g.lb(O3,g.nv);g.k=O3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;N3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.BJ();this.hn("play");this.isPaused()&&this.hn("resume");this.j=1;var b=g.fb(this);b in L3||(L3[b]=this);mnb();nnb(this,a);return!0};
g.k.stop=function(a){N3(this);this.j=0;a&&(this.progress=1);onb(this,this.progress);this.onStop();this.Yq()};
g.k.pause=function(){this.isPlaying()&&(N3(this),this.j=-1,this.hn("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.hn("destroy");O3.Qf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.FL=function(){this.hn("animate")};
g.k.hn=function(a){this.dispatchEvent(new pnb(a,this))};
g.lb(pnb,g.zb);g.lb(P3,O3);P3.prototype.C=function(){};
P3.prototype.FL=function(){this.C();P3.Qf.FL.call(this)};
P3.prototype.Yq=function(){this.C();P3.Qf.Yq.call(this)};
P3.prototype.BJ=function(){this.C();P3.Qf.BJ.call(this)};
g.lb(qnb,P3);qnb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(tnb,g.I);g.k=tnb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.kC(a,b,c);this.j.push(a);return a};
g.k.cJ=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=knb(a,b,c);this.j.push(a);return a};
g.k.Rc=function(a){g.lC(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.lC(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.I.prototype.va.call(this)};g.x(wnb,g.NV);g.k=wnb.prototype;g.k.load=function(){g.NV.prototype.load.call(this);if(!S3(this)){var a=g.wUa(this.player.getVideoData());a?(a=vnb(a,xnb(this)),T3(this,a,!1)):ynb(this)}};
g.k.unload=function(){T3(this,null);this.C&&(this.C.abort(),this.C=null);g.NV.prototype.unload.call(this)};
g.k.Lh=function(a,b){return S3(this)?"loadCustomEndscreenRenderer"===a?(a=vnb(b,"new"),T3(this,a),!0):null:null};
g.k.getOptions=function(){return S3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Vb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Rob.length;f++){var h=Math.abs(b.width-Rob[f]);if(-1===e||d>=h)e=f,d=h}d=Sob[e];this.B&&g.os(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.zs(e.element,m,f);g.vs(e.element,n,p);g.lv(e.element,Tob);256<m||256<f?g.bv(e.element,"ytp-ce-large-round"):96<m||96<f?g.bv(e.element,"ytp-ce-medium-round"):g.bv(e.element,"ytp-ce-small-round");g.lv(e.element,Uob);m=h.left+h.width/2;h=h.top+l/2;g.bv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.lv(e.element,Sob);g.bv(e.element,d);(e=g.yf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.os(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())X3(this,this.endscreen.impressionUrls),(a=g.bF())&&this.endscreen.visualElement&&g.rF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.bv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.bv(b,"ytp-ce-shown");X3(this,c.impressionUrls);(b=g.bF())&&g.rF(b,c.visualElement);this.player.U().N&&this.player.ib("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.dv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.dv(b,"ytp-ce-shown");this.player.U().N&&this.player.ib("endscreenelementhidden",a)}};
g.k.kba=function(a){var b=this;a.target===window&&(new g.Uu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.lv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Rob=[346,426,470,506,570,640,853,1280,1920],Sob="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Uob=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Tob=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Lnb={Qua:"current",OVa:"new"};var Nnb={CLOSE:"close",FZa:"openUrl",SUBSCRIBE:"subscribe"},Onb={Ysa:"click",CLOSE:"close",PGa:"hidden",H4a:"rollOut",I4a:"rollOver",x6a:"shown"};Qnb.prototype.Pe=function(){var a=Rnb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Oob={una:"anchored",P1:"branding",CHANNEL:"channel",Gua:"cta",SGa:"highlightText",WKa:"label",PLAYLIST:"playlist",POPUP:"popup",x9a:"speech",SUBSCRIBE:"subscribe",ncb:"title",VIDEO:"video",Ojb:"website"},Nob={P1:"branding",Dqa:"card",Qwa:"drawer",RGa:"highlight",iRa:"marker",T2a:"promotion",TEXT:"text",vlb:"widget"};g.x(d4,g.I);g.k=d4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.FJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Va.set(a,d);e&&this.Za.set(a,e);this.context.J.nf([a])};
g.k.UF=function(){this.context.B.subscribe("resize",this.gH,this)};
g.k.Gb=function(){return this.element};
g.k.GL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Rf(this.Gb())};
g.k.gH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Z3(a);if(f){var h=Ynb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Lf||!1,n=g.lB(f||"");m&&n&&(n.v||n.list)?e.context.J.Fo(n.v,b,n.list,!1):g.PG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);p4(this.context.logger,c,l,d);Xnb(f)||(c=g.bF(),d=b.itct,c&&d&&g.uF(c,g.$E(d)))}};
g.k.va=function(){this.Va.clear();this.Za.clear();g.I.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.O(this,a);return a.element};g.x($nb,d4);g.k=$nb.prototype;g.k.Us=function(){this.ra&&i4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.As(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.gH=function(){var a=this.isAvailable();g.Bs(this.Gb(),a);g.mv(this.context.J.getRootNode(),g.fZ.IV_DRAWER_ENABLED,a);J3(this.J)};
g.k.destroy=function(){this.J.kB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.jE(this.oa);g.qC(this.Qa);this.Ta&&this.Ta.dispose();this.G&&this.G.dispose();d4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.Df.startMs>c.Df.startMs||a.Df.startMs===c.Df.startMs&&a.Df.timestamp>=c.Df.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.U5=function(){if(this.C){p4(this.context.logger,m4(this).bj.close);var a=g.bF();a&&this.N&&g.uF(a,this.N);h4(this)}};
g.k.s6=function(){g.mv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.P8=function(){var a=g.bF(),b=m4(this);b=b?b.If:this.If;a&&b&&g.sF(a,[b])};
g.k.O8=function(){var a=g.bF(),b=m4(this);b=b?b.If:this.If;a&&b&&g.tF(a,[b])};
g.k.F2=function(){var a=m4(this);p4(this.context.logger,a.bj.A0);var b=g.bF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Ij&&c.push(a.Ij);a.If&&c.push(a.If);0<c.length&&g.sF(b,c)}else g.sF(b,[a.Ij,a.If])};
g.k.Q8=function(){var a=g.bF(),b=m4(this);a&&b&&g.tF(a,[b.Ij])};
g.k.E2=function(a){var b=m4(this),c=g.bF();this.j?a?(a=this.context.logger,p4(a,b.bj.WK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ij&&g.uF(c,b.Ij)):(a=this.context.logger,p4(a,b.bj.WK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.If&&g.uF(c,b.If)):(a=this.context.logger,p4(a,b.bj.WK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.If&&g.uF(c,this.If))};g.x(n4,d4);n4.prototype.UF=function(){d4.prototype.UF.call(this);oob(this)};
n4.prototype.show=function(){d4.prototype.show.call(this);var a=g.bF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sF(a,[g.$E(b.itct)])};
n4.prototype.hide=function(){d4.prototype.hide.call(this);var a=g.bF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tF(a,[g.$E(b.itct)])};g.x(o4,n4);o4.prototype.gx=function(){g.bv(this.Gb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Bs(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Gb().appendChild(b);var c=this.annotation.Pe();c&&e4(this,b,c,this.annotation.id,a.session_data);sob(this,a)};
o4.prototype.show=function(){if(!this.isActive&&(n4.prototype.show.call(this),this.N||(this.gx(),this.N=!0),g.Bs(this.Gb(),!0),this.isActive=!0,this.B)){try{pob(this,this.B)}catch(a){}g.bv(this.context.J.getRootNode(),"ytp-branding-shown")}};
o4.prototype.hide=function(){this.isActive&&(n4.prototype.hide.call(this),g.Bs(this.Gb(),!1),this.isActive=!1,g.dv(this.context.J.getRootNode(),"ytp-branding-shown"))};
o4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);n4.prototype.destroy.call(this)};g.x(uob,n4);g.k=uob.prototype;
g.k.gx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Gb().setAttribute("aria-hidden","true");this.Gb().setAttribute("aria-label","Promotion");this.Gb().tabIndex=0;var e=this.annotation.Pe(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&e4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Qe(f,Z3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&e4(this,
this.Gb(),e,this.annotation.id,b.session_data,void 0,c)}g.bv(this.j,"iv-click-target");e&&e4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.bv(this.j,"iv-click-target"),e&&e4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){xob(a,5E3,q)});
c.appendChild(this.B);g.Bs(this.B,!1);this.context.j.listen(this.Gb(),"mouseover",this.L7,this);this.context.j.listen(this.Gb(),"mouseout",this.K7,this);this.context.j.listen(this.Gb(),"touchend",function(q){xob(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.G7:this.F7,this);c.appendChild(this.C);g.cv(this.Gb(),d);h&&(g.Kf(this.Gb(),h),n&&h.appendChild(n));g.Kf(this.Gb(),this.N);g.Kf(this.Gb(),c)};
g.k.show=function(){this.isActive||(n4.prototype.show.call(this),this.Y||(this.gx(),this.Y=!0),g.Bs(this.Gb(),!0),g.yg(function(){g.dv(this.Gb(),"iv-promo-inactive")},100,this),this.Gb().removeAttribute("aria-hidden"),this.isActive=!0,zob(this),vob(this),wob(this,this.K))};
g.k.hide=function(){this.isActive&&(g.bv(this.Gb(),"iv-promo-inactive"),this.isActive=!1,this.Gb().setAttribute("aria-hidden","true"))};
g.k.GL=function(a,b,c,d,e,f){return this.isCollapsed?!1:n4.prototype.GL.call(this,a,b,c,d,e,f)};
g.k.L7=function(a){this.Z=!0;xob(this,500,a)};
g.k.K7=function(){this.Z=!1;yob(this)};
g.k.F7=function(a){a.stopPropagation();this.hide()};
g.k.G7=function(a){a.stopPropagation();zob(this);this.isCollapsed=!0;g.bv(this.Gb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();n4.prototype.destroy.call(this)};g.x(Bob,g.NV);g.k=Bob.prototype;g.k.Lh=function(a,b){if(!Qob(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.j2(b))&&Gob(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(dob(this.j,b),J3(this.player)),!0}return null};
g.k.getOptions=function(){return Qob(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Vt=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.JT(b)||g.TT(this.player.app)?!1:1===c&&!b.jV||a.Ma.get(b.videoId)||g.xT(b)||g.xUa(b)?!0:!1};
g.k.KJ=function(){if(this.C){var a=this.player.kb().getVideoContentRect(!0);g.zs(this.C.element,a.width,a.height);g.vs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.yn();a=this.j;b=b.width;g.mv(a.D,"iv-drawer-small",426>=b);g.mv(a.D,"iv-drawer-big",1280<=b)}};
g.k.G2=function(a){Dob(this,a.state);g.uG(a.state,2)&&(this.Ik()&&this.To()&&2!==this.player.getPresentingPlayerType()&&this.lB(!1),this.kB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.vB(h)&&h.responseXML?h.responseXML:null)&&(Gob(b,h),g.bv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.NV.prototype.load.call(this);Dob(this,this.player.Tb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.JC()&&(a=Hob(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Ma.get(d);f&&Iob(e,f);f=f&&(f.cN||f.lH);if(!c.Fx||f)c.Ta?Eob(this,c.Ta,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.wT(h))&&!b.oa&&Mob(b,h)},this.player.addEventListener("videodatachange",this.K));
g.hU(this.player,this.C.element,4);this.KJ();(f=g.xT(c))&&Lob(this,f);(f=g.xUa(c))&&f.featuredChannel&&Pob(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Ug=g.Af("ytp-cards-button",this.player.getRootNode());g.wT(c)&&Mob(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&Eob(this,b.Ta,a)};
g.k.unload=function(){this.player.uf("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,J3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.oa=!1;this.N={};this.B.hide();g.NV.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.PZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Job(this):this.load())};
g.k.Ik=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.oa};
g.k.To=function(){return!!this.j&&this.j.C};
g.k.lB=function(a,b,c){b=void 0===b?!1:b;this.Ik();this.j&&(a?c?g4(this.j,c,b):g4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):h4(this.j))};
g.k.kB=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Ma.unsubscribe("vast_info_card_add",this.PZ,this);g.dv(this.player.getRootNode(),g.fZ.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Mu,c=0,d=a.length;c<d;c++)b.Oj(a[c]);this.ra.length=0;g.NV.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.O(this,a);return a.element};g.MV("annotations_module",Bob);g.MV("creatorendscreen",wnb);})(_yt_player);
